image: klakegg/hugo:ext-alpine

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - hugo --minify --baseURL "${CI_PAGES_URL}"
  artifacts:
    paths:
      - public
  only:
    - main