baseURL = 'https://stephanievidonne.com/'
languageCode = 'fr-FR'
title = 'Stéphanie Vidonne'
theme = "my-theme"

[params]
  description = "Auteure"
  keywords = "keyword1, keyword2, keyword3"
  author = "Stéphanie Vidonne"